#!/bin/bash

#SBATCH --job-name=FRICOSIPY
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err	
#SBATCH --time=30-00:00:00
#SBATCH --ntasks=1              # Keep equal to 1!
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=30G
#SBATCH --account=unifr
#SBATCH --mail-type=END
#SBATCH --mail-user=marcus.gastaldello@unifr.ch
#SBATCH --partition=new

python FRICOSIPY.py

# Note: if you use too many CPUs/workers than required you get the Event Loop was Unresponsive in Worker Error!