#!/bin/bash

#SBATCH --job-name=Illumination
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err	
#SBATCH --time=6-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=120G
#SBATCH --mail-type=END
#SBATCH --mail-user=marcus.gastaldello@unifr.ch
#SBATCH --account=unifr
#SBATCH --partition=new

python create_illumination_netcdf.py -s /home/gastalm/Data/static/Static_Monte_Rosa_25m.nc -i /home/gastalm/Data/illumination/Illumination_Monte_Rosa_25m.nc