#!/bin/bash

#SBATCH --job-name=aws2cosipytest01
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err	
#SBATCH --time=6-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=120G
#SBATCH --mail-type=END
#SBATCH --mail-user=marcus.gastaldello@unifr.ch
#SBATCH --account=unifr
#SBATCH --partition=new

python3 create_static_netcdf.py -c /home/gastalm/Data/static/CSV/CSV_Colle_Gnifetti_Points_20m.csv -s /home/gastalm/Data/static/Static_Colle_Gnifetti_Points.nc