#!/bin/bash

#SBATCH --job-name=aws2cosipytest01
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err	
#SBATCH --time=6-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=120G
#SBATCH --mail-type=END
#SBATCH --mail-user=marcus.gastaldello@unifr.ch
#SBATCH --account=unifr
#SBATCH --partition=new

python create_meteo_netcdf.py -c /home/gastalm/Data/meteo/Meteorological_Data/Colle_Gnifetti_Climate_OSU_1H_1939-23.csv -m /home/gastalm/Data/meteo/Meteo_Colle_Gnifetti_OSU_1H_1939-23.nc -b 19390101 -e 20231231